[theme]
base = "light"
primaryColor = "#147D71"
backgroundColor = "#F7F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18283B"
font = "sans serif"

[server]
headless = true
maxUploadSize = 20

[browser]
gatherUsageStats = false
